import { Router } from 'express';
import healthRoutes from './health.routes';
import userRoutes from './user.routes';
import authRoutes from './auth.routes';
import productRoutes from './product.routes';
import orderRoutes from './order.routes';
import savingsRoutes from './savings.routes';
import cartRoutes from './cart.routes';
import adminRoutes from './admin.routes';
import miscRoutes from './misc.routes';
import couponRoutes from './coupon.routes';
import paymentRoutes from './payment.routes';
import wishlistRoutes from './wishlist.routes';
import silverRateRoutes from './silverrate.routes';
import goldRateRoutes from './goldrate.routes';
import returnRoutes from './return.routes';
import metalRateRoutes from './metalrate.routes';
import deliveryRoutes from './delivery.routes';
import shippingRoutes from './shipping.routes';
import storeConfigRoutes from './storeConfig.routes';
import giftVoucherRoutes from './giftVoucher.routes';
import pricingConfigRoutes from './pricingConfig.routes';
import deliveryConfigRoutes from './deliveryConfig.routes';
import stallConfigRoutes from './stallConfig.routes';
import invoiceConfigRoutes from './invoiceConfig.routes';
import whatsappWebhookRoutes from './whatsappWebhook.routes';
import schemePlanRoutes from './schemePlan.routes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/products', productRoutes);
router.use('/orders', orderRoutes);
router.use('/savings', savingsRoutes);
router.use('/cart', cartRoutes);
router.use('/coupons', couponRoutes);
router.use('/payments', paymentRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/silver-rates', silverRateRoutes);
router.use('/gold-rates', goldRateRoutes);
router.use('/metal-rates', metalRateRoutes);
router.use('/returns', returnRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/shipping', shippingRoutes);
router.use('/store-config', storeConfigRoutes);
router.use('/gift-vouchers', giftVoucherRoutes);
router.use('/pricing-config', pricingConfigRoutes);
router.use('/delivery-config', deliveryConfigRoutes);
router.use('/stall-config', stallConfigRoutes);
router.use('/invoice-config', invoiceConfigRoutes);
router.use('/scheme-plans', schemePlanRoutes);
router.use('/webhooks/whatsapp', whatsappWebhookRoutes);
router.use('/admin', adminRoutes);
router.use('/', miscRoutes);

export default router;
